# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86a6b52339dd3f448f3645f8fed9760a698be82289d10843259ce7ef7f0105cb105df32b0e87d24cf07d22101fe05d18493c6c776dd119f6f1f834fe7a9bdf81

test:
  secret_key_base: 8da9a685dbbfca41eb055cda92b8e00b35a4740f2da030492533a24753619c00a551ac7f2b06026ba5711bc58882fa7e502358a47a03175b670e079fbaa3021e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
